'use strict';

const { DataTypes, Model } = require('sequelize');

module.exports = (sequelize) => {
  class PayrollItem extends Model {
    get isAutoGenerated() {
      return this.source !== 'manual';
    }
  }

  PayrollItem.init({
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
    },
    payslip_id: {
      type: DataTypes.UUID,
      allowNull: false,
    },
    type: {
      type: DataTypes.ENUM('incentive', 'penalty', 'bonus', 'reimburse'),
      allowNull: false,
    },
    source: {
      type: DataTypes.ENUM('manual', 'auto_late', 'auto_reimburse', 'auto_leave'),
      allowNull: false,
      defaultValue: 'manual',
    },
    amount: {
      type: DataTypes.DECIMAL(15, 2),
      allowNull: false,
      validate: { min: 0 },
    },
    description: {
      type: DataTypes.TEXT,
      allowNull: true,
    },
    // Polymorphic reference ke sumber data
    ref_id: {
      type: DataTypes.UUID,
      allowNull: true,
    },
    ref_type: {
      type: DataTypes.STRING(50),
      allowNull: true,
    },
    created_by: {
      type: DataTypes.UUID,
      allowNull: true,
    },
  }, {
    sequelize,
    modelName: 'PayrollItem',
    tableName: 'payroll_items',
    underscored: true,
    timestamps: true,
    createdAt: 'created_at',
    updatedAt: false,
    scopes: {
      incentives: { where: { type: 'incentive' } },
      penalties: { where: { type: 'penalty' } },
      bonuses: { where: { type: 'bonus' } },
      reimbursements: { where: { type: 'reimburse' } },
      auto: { where: { source: ['auto_late', 'auto_reimburse', 'auto_leave'] } },
      manual: { where: { source: 'manual' } },
    },
  });

  return PayrollItem;
};
